version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username "gurkasathish" --password "sathishgurka"
  build:
    commands:
      - echo Building Docker image...
      - docker build -t "gurkasathish/candycrush-clone:v1" .
artifacts:
    files:
         - '**/*'



